#!/bin/bash

export PATH=$PATH:yices-2.0.0/bin
CLASSPATH=out/production/tests
iter=$1
YOURPGM=$2

rm -f inputs
rm -f history

i=1

echo "Now testing $YOURPGM"

while [ $i -le $iter ]
do
	echo "[Input $i]"
    java -Djanala.conf=catg.conf -javaagent:"lib/iagent.jar"  -cp "$CLASSPATH:lib/asm-all-3.3.1.jar:out/production/janala" -ea $YOURPGM
    java -Djanala.conf=catg.conf -Djanala.mainClass=$YOURPGM -Djanala.iteration=$i -cp "$CLASSPATH:lib/asm-all-3.3.1.jar:lib/trove-3.0.3.jar:lib/choco-solver-2.1.4.jar:lib/iagent.jar" -ea janala.interpreters.LoadAndExecuteInstructions
	if  [ -e "history" ]
	then
		echo -n ""
	else
		exit
	fi


i=$((i+1))
done

